// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5fSm6z_sg377z08r6oq8zi0h0oHmQ--g',
    appId: '1:694517299538:android:b038ea0d8f54645a16228b',
    messagingSenderId: '694517299538',
    projectId: 'vehicle-tracking-test-650e9',
    databaseURL:
        'https://vehicle-tracking-test-650e9-default-rtdb.firebaseio.com',
    storageBucket: 'vehicle-tracking-test-650e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI_2y8I-9dRvnaX5tqZcr2sBjHFbHzl1E',
    appId: '1:694517299538:ios:26f70a7312a437c416228b',
    messagingSenderId: '694517299538',
    projectId: 'vehicle-tracking-test-650e9',
    databaseURL:
        'https://vehicle-tracking-test-650e9-default-rtdb.firebaseio.com',
    storageBucket: 'vehicle-tracking-test-650e9.firebasestorage.app',
    iosBundleId: 'com.example.vehicleTracker',
  );
}
